dist: xenial
os: linux

language: node_js
node_js:
  - "10"

env:
  global:
    - VAR=val

services:
  - postgresql
  - mysql

before_install:
  - mysql -e 'SET PASSWORD FOR "root"@"localhost" = PASSWORD("");' -uroot
  - mysql -e "create database gybson_test"
  - psql -c 'create database travis_ci_test;' -U postgres

script: npm run test

notifications:
  email: false