dist: trusty
sudo: required

language: node_js
node_js:
  - "8"
  - "10"

env:
  global:
    - VAR=val

services:
  - postgresql
  - mysql

addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
  postgresql: "9.6"

before_install:
  - mysql -e 'SET PASSWORD FOR "root"@"localhost" = PASSWORD("");' -uroot
  - mysql -e "create database gybson_test"
  - psql -c 'create database travis_ci_test;' -U postgres

script: npm run coverage:ci

notifications:
  email: false