/* Auto generated by relational-schema (https://github.com/MattGson/relational-schema) --- DO NOT MODIFY */

/* eslint-disable */
import { GybsonBase } from '../../src/query-client';
import Teams from './Teams';
import TeamMembers from './TeamMembers';
import TeamMembersPositions from './TeamMembersPositions';
import Users from './Users';
import Posts from './Posts';

export class GybsonClient extends GybsonBase {
    public readonly Teams = new Teams(this.clientConfig);
    public TeamMembers = new TeamMembers(this.clientConfig);
    public TeamMembersPositions = new TeamMembersPositions(this.clientConfig);
    public Users = new Users(this.clientConfig);
    public Posts = new Posts(this.clientConfig);
}
