/* Auto generated by relational-schema (https://github.com/MattGson/relational-schema) --- DO NOT MODIFY */

/* eslint-disable */
import { GybsonBase } from '../../src/query-client';
import Teams from './Teams';
import TeamMembers from './TeamMembers';
import TeamMembersPositions from './TeamMembersPositions';
import Users from './Users';
import Posts from './Posts';
export * from './Teams';
export * from './TeamMembers';
export * from './TeamMembersPositions';
export * from './Users';
export * from './Posts';

export class GybsonClient extends GybsonBase {
    public readonly Teams = new Teams(this.clientConfig);
    public readonly TeamMembers = new TeamMembers(this.clientConfig);
    public readonly TeamMembersPositions = new TeamMembersPositions(this.clientConfig);
    public readonly Users = new Users(this.clientConfig);
    public readonly Posts = new Posts(this.clientConfig);
}
