import _ from 'lodash';
import fs from 'fs-extra';
import path from 'path';
import { prettier } from './config';
// @ts-ignore
import { format } from 'prettier';

export const PascalCase = (name: string): string => {
    return _.upperFirst(_.camelCase(name));
};

/**
 * Write to a typescript file
 * @param content
 * @param directory
 * @param filename
 */
export async function writeTypescriptFile(content: string, directory: string, filename: string) {
    const fileHeader = `
         /* Auto generated by Gybson (https://github.com/MattGson/Gybson) --- DO NOT MODIFY */
        
        /* eslint-disable */
    `;

    // append creates files if they don't exist - write overwrites contents
    await fs.appendFile(path.join(directory, filename), '');
    await fs.writeFile(
        path.join(directory, filename),
        format(fileHeader + content, { parser: 'typescript', ...prettier }),
    );
}
